[project]
name = "blog"
version = "0.0.1"
description = ""
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jinja2>=3.1.6",
  "markdown>=3.10.2",
  "pillow>=12.2.0",
  "pygments>=2.20.0",
  "pymdown-extensions>=10.21.2",
  "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "accessible-pygments>=0.0.5",
]
