name: CI
permissions:
  contents: read
  deployments: write
on:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: pentest-party (Production)
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/setup-uv@v5
    - uses: actions/setup-python@v5
      with:
        python-version-file: .python-version
    - run: uv run ./build.py
    - run: ./minify.sh
    - uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        command: pages deploy ./public --project-name pentest-party
